services:
  aea5:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/aea5
      - /aea5/node_modules
    ports:
      - "5175:5175"
    environment:
      - ELECTRON_START_URL=http://localhost:5175
    tty: true
    stdin_open: true
    command: npm run dev