services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Mapear 5173 (host) a 5173 (contenedor)
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run start # Solo ejecuta Vite